export default {
  type: 'demo',
  root: {
    kind: 'box',
    className: 'h-48 w-80',
    children: [
      {
        kind: 'proto',
        prototypeId: 'brutalist-scroll-area-root',
        children: [
          {
            kind: 'proto',
            prototypeId: 'brutalist-scroll-area-viewport',
            children: [
              {
                kind: 'box',
                className: 'flex flex-col gap-3 p-3 text-sm leading-6',
                children: [
                  'Scrollable conversation content line 1 — dense SaaS panel row.',
                  'Scrollable conversation content line 2 — dense SaaS panel row.',
                  'Scrollable conversation content line 3 — dense SaaS panel row.',
                  'Scrollable conversation content line 4 — dense SaaS panel row.',
                  'Scrollable conversation content line 5 — dense SaaS panel row.',
                  'Scrollable conversation content line 6 — dense SaaS panel row.',
                  'Scrollable conversation content line 7 — dense SaaS panel row.',
                  'Scrollable conversation content line 8 — dense SaaS panel row.',
                  'Scrollable conversation content line 9 — dense SaaS panel row.',
                  'Scrollable conversation content line 10 — dense SaaS panel row.',
                  'Scrollable conversation content line 11 — dense SaaS panel row.',
                  'Scrollable conversation content line 12 — dense SaaS panel row.',
                  'Scrollable conversation content line 13 — dense SaaS panel row.',
                  'Scrollable conversation content line 14 — dense SaaS panel row.',
                  'Scrollable conversation content line 15 — dense SaaS panel row.',
                  'Scrollable conversation content line 16 — dense SaaS panel row.',
                  'Scrollable conversation content line 17 — dense SaaS panel row.',
                  'Scrollable conversation content line 18 — dense SaaS panel row.',
                  'Scrollable conversation content line 19 — dense SaaS panel row.',
                  'Scrollable conversation content line 20 — dense SaaS panel row.',
                  'Scrollable conversation content line 21 — dense SaaS panel row.',
                  'Scrollable conversation content line 22 — dense SaaS panel row.',
                  'Scrollable conversation content line 23 — dense SaaS panel row.',
                  'Scrollable conversation content line 24 — dense SaaS panel row.',
                  'Scrollable conversation content line 25 — dense SaaS panel row.',
                  'Scrollable conversation content line 26 — dense SaaS panel row.',
                  'Scrollable conversation content line 27 — dense SaaS panel row.',
                  'Scrollable conversation content line 28 — dense SaaS panel row.',
                  'Scrollable conversation content line 29 — dense SaaS panel row.',
                  'Scrollable conversation content line 30 — dense SaaS panel row.',
                  'Scrollable conversation content line 31 — dense SaaS panel row.',
                  'Scrollable conversation content line 32 — dense SaaS panel row.',
                  'Scrollable conversation content line 33 — dense SaaS panel row.',
                  'Scrollable conversation content line 34 — dense SaaS panel row.',
                  'Scrollable conversation content line 35 — dense SaaS panel row.',
                  'Scrollable conversation content line 36 — dense SaaS panel row.',
                  'Scrollable conversation content line 37 — dense SaaS panel row.',
                  'Scrollable conversation content line 38 — dense SaaS panel row.',
                  'Scrollable conversation content line 39 — dense SaaS panel row.',
                  'Scrollable conversation content line 40 — dense SaaS panel row.',
                ],
              },
            ],
          },
          {
            kind: 'proto',
            prototypeId: 'brutalist-scroll-area-scrollbar',
            props: { orientation: 'vertical' },
            children: [{ kind: 'proto', prototypeId: 'brutalist-scroll-area-thumb' }],
          },
          { kind: 'proto', prototypeId: 'brutalist-scroll-area-corner' },
        ],
      },
    ],
  },
};
