/* This file is generated by scripts/components/generate-shadcn-component-presets.mjs. */
/* Edit packages/prototypes/shadcn/src/component-presets.ts instead. */

export const SHADCN_COMPONENT_PRESET_RECIPES = {
  'shadcn-switch': {
    'kind': 'replaceable-default-part',
    'exportName': 'ShadcnSwitch',
    'rootPrototype': 'shadcnSwitchRoot',
    'defaultPartPrototype': 'shadcnSwitchThumb',
    'inputName': 'thumb',
    'elementName': 'proto-ui-shadcn-switch',
    'omissionAttribute': 'data-pui-no-default-thumb',
  },
  'shadcn-dialog': {
    'kind': 'replaceable-default-part',
    'exportName': 'ShadcnDialogContent',
    'rootPrototype': 'shadcnDialogContent',
    'defaultPartPrototype': 'shadcnDialogCloseIcon',
    'inputName': 'close',
    'elementName': 'proto-ui-shadcn-dialog-content',
    'omissionAttribute': 'data-pui-no-default-close',
  },
} as const;
